# SPDX-License-Identifier: Apache-2.0
# Copyright (c) VEXXHOST, Inc.

galaxy_info:
  author: VEXXHOST, Inc.
  description: Ansible role for "support-bundle"
  license: Apache-2.0
  min_ansible_version: 5.5.0
  standalone: false
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies:
  - role: vexxhost.containers.download_artifact
    download_artifact_url: "{{ support_bundle_download_url }}"
    download_artifact_dest: "{{ support_bundle_download_dest }}"
    download_artifact_unarchive_include: support-bundle
    download_artifact_checksum: "sha256:{{ support_bundle_binary_checksum }}"
    download_artifact_owner: root
    download_artifact_mode: "0755"
